### PR TITLE
Fix error in Ember 2.0

### LINKED ISSUE #5: Not working in ember 2.0
In Ember 2.0.3 [this line](https://github.com/salsify/ember-css-modules/blob/master/addon/mixins/component-lookup-mixin.js#L9) raises an error because `owner` is a `Container` instance and doesn't have a `register` method.

Will try to fix it, but I mention in case I don't have time today and you want to tackle it.

### PR DESCRIPTION
**Pull request by cibernox**
Closes #5

### CODE REVIEW

**Comment by dfreeman** [comment]
And here I thought testing in 1.13 and current 2.x would protect against this kind of issue... silly me. Out of curiosity, are you stuck on 2.0.x for a particular reason, or just haven't upgraded yet?

Thanks for the fix! It looks like you've annoyed JSHint, but if you get that fixed up I'll merge and publish a bugfix release.

**Comment by cibernox** [comment]
@dfreeman I'm just upgrading one version at a time and fixing deprecations on each step. By the end of the week I hope to be in 2.4

Fixed the JSHint error, should be green now.

**Comment by dfreeman** [comment]
Perfect, thanks (and thank you for squashing)! Hopefully you won't find any other surprises in 2.1 or 2.2...

**Comment by dfreeman** [comment]
Published as `0.2.1`

**Pull request merged**
