### PR TITLE
Allow '.' in the configured module extension

### PR DESCRIPTION
**Pull request by jessedijkstra**
@dfreeman Seems to work! thanks!

### CODE REVIEW

**Comment by jessedijkstra** [comment]
Quite sure the resolveRegistration is a bit wonky. When I compile the stylesheets it does appear in the stylesheet and does create a tmp broccoli file for the files.

**Comment by jessedijkstra** [comment]
nvm, turns out NPM didn't really like me importing a branch. Seems to work! Thanks!

**Comment by dfreeman** [comment]
@jessedijkstra Thanks for your patience on this — just went out in 0.4.4

**Comment by jessedijkstra** [comment]
@dfree Thanks! Used in production through a Git NPM module, will default back to the NPM module :)

**Pull request closed without merging**
