### PR TITLE
[WIP] localClassNameBindings & localClassNames

### PR DESCRIPTION
**Pull request by mattsacks**
This PR will add support for `localClassNames` and `localClassNameBindings` as described in #26. 

**TODO:**
- [ ] Get feedback
- [ ] Add support for `localClassNames`
- [ ] Decide if overwriting `classNames` is appropriate
- [ ] Tests!

/cc @dfreeman @max @alvinvogelzang @ynnoj

### CODE REVIEW

**Comment by dfreeman** [comment]
@mattsacks Thanks for getting the ball rolling on this! Super excited to see this feature start to come together.

I had been guessing that `localClassNames` and `localClassNameBindings` could be implemented in terms of `classNameBindings`, something along the lines of:

```
localClassNames: ['one']                ==> classNameBindings: ['styles.one']
localClassNameBindings: ['two']         ==> classNameBindings: [`two:${styles.two}`]
localClassNameBindings: ['two:abc']     ==> classNameBindings: [`two:${styles.abc}`]
localClassNameBindings: ['two:abc:def'] ==> classNameBindings: [`two:${styles.abc}:${styles.def}`]
```

It's totally possible there are scenarios I'm not accounting for here, though — is there stuff you can do with `classNames` or `classNameBindings` that doesn't translate to the `local` equivalents here?

**Comment by dfreeman** [comment]
Just playing around with what this might look like:
https://ember-twiddle.com/b223f015c9e6e861ceb54e5dbee60c70

**Comment by mattsacks** [comment]
@dfreeman This is awesome! Took me a while to understand what's happening here so I hope you don't mind me asking some questions.

I'm curious about how `concatenatedProperties` works here. Is this intended so that if there are classes mixed from `localClassNames` and `localClassNameBindings`, it will defer to using `localClassNameBindings`?

Also, I'm not sure I understand the use of `trueClass || dasherize(property)`. In what case would the dasherized property be used if a `trueClass` is provided and true?

Thanks so much for sketching this out! It's incredibly helpful for improving my code.

**Comment by dfreeman** [comment]
> I'm curious about how concatenatedProperties works here. Is this intended so that if there are classes mixed from localClassNames and localClassNameBindings, it will defer to using localClassNameBindings?

`concatenatedProperties` makes it so that any subclasses with values for `localClassNames` or `localClassNameBindings` will automatically be added to the superclass's values, rather than overriding them (the same way `classNames` and `classNameBindings` work). It also normalizes the value to be an array, if it's specified at all. In fact, `classNames` is actually the example used [in the documentation for `concatenatedProperties`](http://emberjs.com/api/classes/Ember.CoreObject.html#property_concatenatedProperties).


> Also, I'm not sure I understand the use of trueClass || dasherize(property). In what case would the dasherized property be used if a trueClass is provided and true?

The dasherized property is used if `trueClass` isn't provided at all. I could also (and maybe more clearly) have written that as:

```js
const [property, trueClass = dasherize(property), falseClass] = classNameBinding.split(':');
const binding = [property, this.get(`styles.${trueClass}`)];
```

This makes it so that I can write code like this and automatically bind the `isUrgent` property to the `is-urgent` class (just like the `isUrgent` example in the [doc for `classNameBindings`](http://emberjs.com/api/classes/Ember.View.html#toc_html-code-class-code-attribute)):

```css
.is-urgent {
  color: red;
}
```

```js
localClassNameBindings: ['isUrgent'],
isUrgent: true
```

**Comment by dfreeman** [comment]
@mattsacks Anything I can do to help out here?

**Comment by dfreeman** [comment]
Just released v0.4.3 with support for `localClassNames` and `localClassNameBindings`, so I'm going to go ahead and close this out. Thanks for your help defining this feature!

**Pull request closed without merging**
